### ISSUE TITLE
Update link LP018

### ISSUE THREAD

**Issue by RodrigoDornelles** [arduino/arduino-lint#358]
I even looked for where to do this to make the modification but I didn't find it, the suggested link is outdated.

* **old** <https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name>
* **new** <https://github.com/arduino/library-registry/blob/main/FAQ.md#readme>

```
ERROR: Library name XXX not found in the Library Manager index. Library                                                 
       names are not allowed to change after being added to the index. See:                                             
       https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name (Rule LP018)   
```

**Comment by per1234** [comment]
Hi @RodrigoDornelles. Thanks for your report. This was fixed some time ago: https://github.com/arduino/arduino-lint/commit/453a1785606b84c9e29401e8a46deb337b59f244

Unfortunately there has not been a release since that time so the fix is only available when using the nightly build of Arduino Lint at the moment:
https://arduino.github.io/arduino-lint/latest/installation/#nightly-builds
