### ISSUE TITLE
Documentation and linter setup mismatch

### ISSUE THREAD

**Issue by jonnybergdahl** [arduino/arduino-lint#638]
### Describe the request

The linter have a warning about recommended library name lengths, but the cited documentation says nothing about that. Either the linter setup is wrong, or the documentation is wrong.

### Describe the current behavior

Just submit a library with a lengthy library name.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @jonnybergdahl. Thanks for your suggestion. The reference link is provided to help you to understand how the name is defined. The name length recommendation is only that. It is a completely optional suggestion for those who would like to follow best practices (because displaying excessively long arbitrary library names in the UI of Arduino development software such as Arduino IDE and Arduino CLI can be problematic). Although we do hope that library maintainers will heed these recommendations, you are free to disregard it if you like. Warnings do not have any impact on a library's inclusion in Arduino Library Manager.

>Either the linter setup is wrong

It is not wrong. Arduino Lint't rule was intentionally configured this way according to best practices recommendations from the developers of the official Arduino development tools.

> the documentation is wrong

There is nothing wrong in the linked reference. The best practices optional recommendation for the library name length was intentionally not included in the Arduino Library Specification because this type of suggestion is not appropriate for a formal specification.

It is included in the Arduino Lint documentation:

https://arduino.github.io/arduino-lint/1.2/rules/library/#name-recommended-length-lp010
