### ISSUE TITLE
Specify link to Github, BitBucket or GitLab as requirement for `url` field

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-lint#647]
### Describe the request

Add rule so that the linter checks for a link to Github, BitBucket or GitLab as in the `url` field. In many instances, for example https://github.com/arduino-libraries/MIDIUSB/blob/f9bcc4eaf7bb983ac1827ccf0f8b833f75001ac2/library.properties the `url` field links to another location.

### Describe the current behavior

According to the library registery [FAQ](https://github.com/arduino/library-registry/blob/ada6b0076e5ceb1b295266359f3332351f0eeeb7/FAQ.md?plain=1#L83):
```
- [ ] The library repository must be hosted on a major Git-hosting website like GitHub, BitBucket or GitLab (other hosting sites may be considered on request).
```

Currently, we do have some useful checks in place for the `url` field. As an example, rule LP040 checks to see if the url is included, but does not check to see if it points back to GitHub, BitBucket or GitLab.

https://github.com/arduino/arduino-lint/blob/c2c82d654e1cf2888112cfc83e3417342b163227/internal/rule/ruleconfiguration/ruleconfiguration.go#L946-L962

### Arduino Lint version

latest

### Operating system

N/A

### Operating system version

N/A

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-lint/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @aliphys. Thanks for your suggestion. 

> According to the library registery [FAQ](https://github.com/arduino/library-registry/blob/ada6b0076e5ceb1b295266359f3332351f0eeeb7/FAQ.md?plain=1#L83):
> ```markdown
> - [ ] The library repository must be hosted on a major Git-hosting website like GitHub, BitBucket or GitLab (other hosting sites may be considered on request).
> ```

That requirement is about the URL that is added to the [`repositories.txt`](https://github.com/arduino/library-registry/blob/main/repositories.txt) file in the [`arduino/library-registry`](https://github.com/arduino/library-registry) repository. The reason for the restrictions on that URL is because the [**libraries-repository-engine**](https://github.com/arduino/libraries-repository-engine) tool must be able to check out the library's Git repository in order to generate the Library Manager index and associated assets.

Since this data is not part of the Arduino library project content, a separate tool is used to check the Library Manager submissions for compliance with this requirement:

https://github.com/arduino/library-registry-submission-parser/blob/1.1.1/main.go#L272-L279

---

The purpose of the `url` field of the [`library.properties`](https://arduino.github.io/arduino-cli/dev/library-specification/#libraryproperties-file-format) metadata file is to provide the library user with a link they can follow to get more information about the library. The library repository might be the place where that information is found, but this is not required. In fact, many of the official Arduino libraries use the URL of the library's page in the Arduino Library Reference ([example](https://github.com/arduino-libraries/Servo/blob/1.2.1/library.properties#L8)), and that is perfectly fine (and in fact superior for the purpose when compared to sending the end user directly to the repository). So there is no need to apply the same requirements on the `url` field of the `library.properties` file as we impose on the registration URL.
